---
- name: Build Hardened Baseline ISO
  hosts: localhost
  connection: local
  vars:
    rhel_packer_file: "baseline-rhel.pkr.hcl"
    cache_dir: "{{ playbook_dir }}/.cache/packer"
    dest_root: "{{ playbook_dir }}/baseline-iso/output-iso/redhat/rhel9"
    ansible_python_interpreter: /usr/bin/python3
    image_output: "rhel9-custom.iso"
    rhel: "{{ ansible_os_family == 'RedHat' }}"
  tasks:
    - name: Ensure python3-dnf is installed for Ansible
      ansible.builtin.yum:
        name: python3-dnf
        state: present

    - name: Ensure required QEMU and dependencies are installed
      ansible.builtin.yum:
        name:
          - bridge-utils
          - dnsmasq
          - ebtables
          - genisoimage
          - libvirt
          - libvirt-client
          - libvirt-daemon
          - qemu-kvm
          - virt-install
          - virt-manager
          - xorriso
        state: present
      become: true

    - name: Start and enable libvirtd service
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true
      become: true

    - name: Remove Packer cache directory before build
      ansible.builtin.file:
        path: "{{ cache_dir }}"
        state: absent

    - name: Verify destination directory exists
      ansible.builtin.stat:
        path: "{{ dest_root }}"
      register: mount_stat

    - name: Create output dir if not found 
      ansible.builtin.stat:
        path: "{{ dest_root }}"
      when: not mount_stat.stat.exists or not mount_stat.stat.isdir

#    - name: Fail if destination directory is missing
#      ansible.builtin.fail:
#        msg: "CRITICAL: {{ dest_root }} is missing. Ensure the ISO storage is mounted."
#      when: not mount_stat.stat.exists or not mount_stat.stat.isdir

    - name: Ensure destination directories exist
      file:
        path: "{{ dest_root }}"
        state: directory
        mode: '0755'
      become: true

    # Initialize Packer dependancies for Custom Image
    - name: Build RedHat Baseline ISO
      command:
        cmd: "packer init {{ ubuntu_packer_file }}" 

    - name: Build Custom Bootable RHEL 9 ISO
      command:
        cmd: "/usr/bin/packer build -var 'destination_path={{ dest_root }}' {{ rhel_packer_file }}"
      register: rhel_build
      changed_when: "'Builds finished.' in rhel_build.stdout"
      environment:
        PACKER_LOG: "1"
        PACKER_LOG_PATH: "./logs/packer-rhel-build.log"

    - name: Show full output of the Packer build
      ansible.builtin.debug:
        msg: "{{ rhel_build.stdout }}"

    - name: Check if Custom RHEL9 ISO Exists
      ansible.builtin.stat:
        path: "{{ dest_root }}/{{ image_output }}"
      register: iso_file_check
      failed_when: not iso_file_check.stat.exists

    - name: Log build completion for audit trail
      lineinfile:
        path: ./build_history.log
        create: yes
        line: "Build successful: {{ ansible_date_time.iso8601 }} - ISO created successfully"
      when: iso_file_check.stat.exists